config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :forecasts, only: [:index, :show]
  root 'navigations#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base.rb
class Base
	
	include ActiveModel::Model
	
	def initialize(hsh={})
		hsh.each do |name, value|
      		send("#{name}=", value) if respond_to?("#{name}=")
    	end
	end
	
end

app/models/city.rb
class City < Base

	attr_accessor :name
	attr_accessor :country	
	
end

app/models/forecast.rb
class Forecast < Base

  

    validates :dt, presence: true
    validates :temp, presence: true
    validates :weather, presence: true
    validates :city, presence: true

  	attr_accessor :dt
  	attr_accessor :pressure
  	attr_accessor :humidity	
  	attr_accessor :speed
  	attr_accessor :deg
  	attr_accessor :clouds	

  	attr_accessor :temp
  	attr_accessor :weather
    attr_accessor :city

    attr_accessor :units
    
  	def initialize(hsh = {})
      super
      self.temp =  Temperature.new(hsh[:temp]) unless hsh[:temp].blank?
      self.weather =  Weather.new(hsh[:weather][0]) unless hsh[:weather].blank? 
      self.city =  City.new(hsh[:city]) unless hsh[:city].blank?
    end

end

app/models/temperature.rb
class Temperature < Base

	attr_accessor :day
	attr_accessor :min	
	attr_accessor :max
	attr_accessor :night
	attr_accessor :eve
	attr_accessor :morn

end

app/models/weather.rb
class Weather < Base

	attr_accessor :main
	attr_accessor :description	
	attr_accessor :icon

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController

  def index

	  	res = ForecastService.find_by_city(params[:search])

	  	if res[:success]
	  		@forecasts = res[:forecasts]
	  		@city = res[:city]
	  	else
	  		flash.now[:error] = "upss.. an error occurred : #{res[:error]}"
	  		render "navigations/home"
	  	end
 	
  end


end

app/controllers/navigations_controller.rb
class NavigationsController < ApplicationController

	def home
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper

	@@allowed_units = %w[metric imperial standard]

	def speed_unit(unit)
		return "meter/sec".html_safe unless @@allowed_units.include? unit
		{metric: "meter/sec", imperial: "foot/sec", standard: "meter/sec"}[unit.to_sym].html_safe
	end

	def temperature_unit(unit)
		return "&deg;".html_safe unless @@allowed_units.include? unit
		{metric: "&deg;C", imperial: "&deg;F", standard: "&deg;K"}[unit.to_sym].html_safe
	end
end

app/views/forecasts/index.html.erb
 <div class="col-12">
<div class="btn-group">
  <%= button_to root_path ,  {controller: "navigations", action: "home", :method => :get, class: 'btn btn-primary'}   do %> 
  	 <div class="glyphicon glyphicon-arrow-left"> Back </div>
  <% end %>
</div>

</div>
<div class="col-12">

	<div class="container-fluid bg-3 text-center"> 
	 	<h1><%= @city.name %> - <%= @city.country %> </h1><br>   
		<div class="row">
		 <% @forecasts.each_with_index do |forecast, index| %> 	

		 			<!-- DISPLAYED INFO -->
				    <div class="col-sm-6 col-md-4 col-lg-3" data-toggle="modal" data-target="#Modal_<%=forecast.dt%>" style="cursor: pointer;">

						      <h3>
						      <%= 
						      if Time.now.strftime("%d/%m/%Y")  == Time.at(forecast.dt).strftime("%d/%m/%Y")  
						      		"Today" 
						      	   else
						      	  	Time.at(forecast.dt).strftime("%A, %d/%m")
						      	   end
						      %>	   
						      </h3>

						     <img src="<%= "http://openweathermap.org/img/w/#{forecast.weather.icon}.png" %>" alt="<%= forecast.weather.main %>" >
							 <p> <%= forecast.temp.day %> <%= temperature_unit(forecast.units) %> </p>
						     <p> <%= forecast.weather.description %> </p>
						     <p> Wind speed <%= forecast.speed %> <%= speed_unit(forecast.units) %> </p>	
		     
				    </div>

				    <!-- MODAL WITH ALL THE INFO-->
				    <div id="Modal_<%=forecast.dt%>" class="modal fade" role="dialog">
						  <div class="modal-dialog">

						    <!-- Modal content-->
						    <div class="modal-content">
						      <div class="modal-header">
						        <button type="button" class="close" data-dismiss="modal">&times;</button>
						        <h3 class="modal-title">
						        	<%=Time.at(forecast.dt).strftime("%A, %d/%m")%>
						        </h3>
						        <h4 class="modal-title">
						        	<%= forecast.city.name %> - <%= forecast.city.country %>
 								</h4> 
						      </div>
						      <div class="modal-body">
						      	<div class="row">
						      		<div class="col-sm-1"></div>
						      		<div class="col-sm-10 text-left">
						      		 	<h2><img src="<%= "http://openweathermap.org/img/w/#{forecast.weather.icon}.png" %>" alt="<%= forecast.weather.main %>" >
						      		 		<%= forecast.weather.main %>
						      		 		<%= forecast.temp.day %> <%= temperature_unit(forecast.units) %>
						      		 		<small> <%= forecast.weather.description %> </small>
						      		 	</h2>
						      		 	
						      		</div>
						      		<div class="col-sm-1"></div>
						      	</div>
					      		<div class="row">
						      		<div class="col-sm-2"></div>
						      		<div class="col-sm-10">
						      		 
						      		 <p class="text-left"> <strong> Pressure: </strong><%= forecast.pressure %> hPa </p>	 
								     <p class="text-left"> <strong> Humidity: </strong><%= forecast.humidity %> % </p>	 
								     <p class="text-left"> <strong> Wind speed: </strong><%= forecast.speed %> <%= speed_unit(forecast.units) %> </p>	
								     <p class="text-left"> <strong> Wind direction: </strong><%= forecast.deg %> degrees </p>	
								     <p class="text-left"> <strong> Cloudiness: </strong><%= forecast.clouds %> % </p>	 

						      		</div>
						      	</div>
					      		<div class="row">
									<div class="col-sm-12">
									 	<h3>Temperatures</h3>
										<table class="table table-condensed">
										    <thead>
										      <tr>
										        <th>Min</th>
										        <th>Max</th>
										        <th>Morning</th>
										        <th>Evening</th>
										        <th>Night</th>										        
										      </tr>
										    </thead>
										    <tbody>
										      <tr class="info text-left">
										        <td> <%= forecast.temp.min%> <%= temperature_unit(forecast.units) %> </td>
 												<td> <%= forecast.temp.max%> <%= temperature_unit(forecast.units) %></td>	
 												<td> <%= forecast.temp.morn%> <%= temperature_unit(forecast.units) %></td>	
 												<td> <%= forecast.temp.eve%> <%= temperature_unit(forecast.units) %></td>	
 												<td> <%= forecast.temp.night%> <%= temperature_unit(forecast.units) %> </td>	 
										      </tr>
										    </tbody>
										  </table>
									</div>
						      	</div>

						      </div>
						      <div class="modal-footer">
						        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						      </div>
						    </div>

						  </div>
					</div>
				 

		 <% end %>
		</div> 
	</div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>16 days Forecast Application</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<!-- Bootstrap grid -->
    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <h2 class="text-center">16 days Forecast Application</h2>
        </div>

        <div class="col-xs-12">
          <% flash.each do |type, message| %>
            <%  style = { error: "alert-danger", success: "alert-success", notice: "alert-info"}[type.to_sym] || type.to_s %>
            <div class="alert <%=style%> fade in">
              <%= message %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/navigations/home.html.erb
<%= form_tag(forecasts_path, :method => "get", id: "search-form") do %>
<!-- <table class="table"> -->
 <div class="col-xs-6">
 <%= text_field_tag :search, params[:search], placeholder: "Search by city, country code ie: 'Dublin,IE' ", class: 'form-control'%>
</div>
 <div class="col-xs-6">
<%= submit_tag "Search", class: 'btn btn-primary' %>
 </div>
<% end %>